/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v{version}/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログイン */
        post: operations["Auth_Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** トークンのリフレッシュ */
        post: operations["Auth_Refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログアウト */
        post: operations["Auth_Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ログインユーザーの取得 */
        get: operations["Auth_GetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プロジェクト一覧取得 */
        get: operations["Projects_List"];
        put?: never;
        /** プロジェクト作成 */
        post: operations["Projects_Launch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プロジェクト単体取得 */
        get: operations["Projects_GetById"];
        put?: never;
        post?: never;
        /** プロジェクト削除 */
        delete: operations["Projects_Delete"];
        options?: never;
        head?: never;
        /** プロジェクト編集 */
        patch: operations["Projects_Update"];
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** プロジェクトメンバー追加 */
        post: operations["Projects_InviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** プロジェクトメンバー削除 */
        delete: operations["Projects_RemoveMember"];
        options?: never;
        head?: never;
        /** プロジェクトロール変更 */
        patch: operations["Projects_ChangeMemberRole"];
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** チケット一覧取得 */
        get: operations["Tickets_List"];
        put?: never;
        /** チケット作成 */
        post: operations["Tickets_Create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** チケット詳細取得 */
        get: operations["Tickets_GetById"];
        put?: never;
        post?: never;
        /** チケット削除 */
        delete: operations["Tickets_Delete"];
        options?: never;
        head?: never;
        /** チケット編集 */
        patch: operations["Tickets_Update"];
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}/tickets/{ticketId}/completion-criteria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** チケット完了条件追加 */
        post: operations["Tickets_AddCompletionCriterion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}/tickets/{ticketId}/completion-criteria/{criterionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** チケット完了条件削除 */
        delete: operations["Tickets_DeleteCompletionCriterion"];
        options?: never;
        head?: never;
        /** チケット完了条件編集 */
        patch: operations["Tickets_EditCompletionCriterion"];
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}/tickets/{ticketId}/completion-criteria/{criterionId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** チケット完了条件完了 */
        post: operations["Tickets_CompleteCriterion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}/tickets/{ticketId}/completion-criteria/{criterionId}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** チケット完了条件再オープン */
        post: operations["Tickets_ReopenCriterion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}/tickets/{ticketId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** チケットコメント投稿 */
        post: operations["Tickets_AddComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/projects/{projectId}/tickets/{ticketId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** チケットコメント削除 */
        delete: operations["Tickets_DeleteComment"];
        options?: never;
        head?: never;
        /** チケットコメント編集 */
        patch: operations["Tickets_EditComment"];
        trace?: never;
    };
    "/api/v{version}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー一覧取得 */
        get: operations["Users_ListAll"];
        put?: never;
        /** ユーザー登録 */
        post: operations["Users_Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v{version}/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** ユーザー削除 */
        delete: operations["Users_Delete"];
        options?: never;
        head?: never;
        /** ユーザー編集 */
        patch: operations["Users_Update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description ログインレスポンスDTO */
        LoginResponse: {
            /**
             * Format: guid
             * @description ユーザーID
             */
            userId?: string;
        };
        /** @description エラーレスポンスDTO */
        ErrorResponse: {
            /** @description エラー詳細 */
            error?: components["schemas"]["ErrorDetail"];
        };
        /** @description エラー詳細DTO */
        ErrorDetail: {
            /** @description エラーコード */
            code?: string;
            /** @description エラーメッセージ */
            message?: string;
            /** @description トレースID */
            traceId?: string;
        };
        /** @description ログインリクエストDTO */
        LoginRequest: {
            /** @description メールアドレス */
            email?: string;
            /** @description パスワード */
            password?: string;
        };
        /** @description リフレッシュレスポンスDTO */
        RefreshResponse: {
            /**
             * Format: guid
             * @description ユーザーID
             */
            userId?: string;
        };
        MeResponse: components["schemas"]["AuditInfoResponse"] & {
            /**
             * Format: guid
             * @description ユーザーID
             */
            id: string;
            /** @description ユーザー名 */
            name: string;
            /** @description Eメール */
            email: string;
            /** @description システムロール */
            role: string;
        };
        /** @description 監査情報レスポンスDTO */
        AuditInfoResponse: {
            /**
             * Format: guid
             * @description 作成者
             */
            createdBy: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            createdAt: string;
            /**
             * Format: guid
             * @description 更新者
             */
            updatedBy: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt: string;
        };
        ProjectResponse: components["schemas"]["AuditInfoResponse"] & {
            /**
             * Format: guid
             * @description プロジェクトID
             */
            id: string;
            /** @description プロジェクト名 */
            name: string;
            /** @description プロジェクト説明 */
            description?: string | null;
        };
        ProjectDetailResponse: components["schemas"]["AuditInfoResponse"] & {
            /**
             * Format: guid
             * @description プロジェクトID
             */
            id: string;
            /** @description プロジェクト名 */
            name: string;
            /** @description プロジェクト説明 */
            description?: string | null;
            /** @description プロジェクトメンバー */
            members: components["schemas"]["ProjectMemberResponse"][];
        };
        ProjectMemberResponse: components["schemas"]["AuditInfoResponse"] & {
            /**
             * Format: guid
             * @description ユーザーID
             */
            userId: string;
            /** @description プロジェクトロール */
            projectRole: string;
        };
        /** @description プロジェクト作成リクエストDTO */
        LaunchProjectRequest: {
            /** @description プロジェクト名 */
            name: string;
            /** @description 説明文 */
            description?: string | null;
        };
        /** @description プロジェクト編集リクエストDTO */
        UpdateProjectRequest: {
            /** @description プロジェクト名 */
            name: string;
            /** @description 説明文 */
            description?: string | null;
        };
        /** @description プロジェクトメンバー追加リクエストDTO */
        InviteMemberRequest: {
            /**
             * Format: guid
             * @description ユーザーID
             */
            userId: string;
            /** @description プロジェクトロール */
            projectRole: string;
        };
        /** @description プロジェクトメンバーロール変更リクエストDTO */
        ChangeMemberRoleRequest: {
            /** @description プロジェクトロール */
            projectRole: string;
        };
        /** @description ページネーションレスポンスDTO */
        PaginatedResponseOfTicketResponse: {
            /** @description ページネーションアイテム */
            items: components["schemas"]["TicketResponse"][];
            /**
             * Format: int32
             * @description トータルカウント
             */
            totalCount: number;
            /**
             * Format: int32
             * @description ページ番号
             */
            pageNumber: number;
            /**
             * Format: int32
             * @description ページサイズ
             */
            pageSize: number;
            /**
             * Format: int32
             * @description トータルページ数
             */
            totalPages: number;
        };
        TicketResponse: components["schemas"]["AuditInfoResponse"] & {
            /**
             * Format: guid
             * @description チケットID
             */
            id: string;
            /**
             * Format: guid
             * @description プロジェクトID
             */
            projectId: string;
            /** @description チケットタイトル */
            title: string;
            /**
             * Format: guid
             * @description 担当者ID
             */
            assigneeId?: string | null;
            /**
             * Format: date
             * @description 開始日
             */
            startDate?: string | null;
            /**
             * Format: date
             * @description 終了日
             */
            endDate?: string | null;
            /** @description ステータス */
            status: string;
        };
        /**
         * @description ソート順
         * @enum {string}
         */
        SortOrder: "Asc" | "Desc";
        TicketDetailResponse: components["schemas"]["AuditInfoResponse"] & {
            /**
             * Format: guid
             * @description チケットID
             */
            id: string;
            /**
             * Format: guid
             * @description プロジェクトID
             */
            projectId: string;
            /** @description チケットタイトル */
            title: string;
            /** @description チケット説明 */
            description: string;
            /**
             * Format: guid
             * @description 担当者ID
             */
            assigneeId?: string | null;
            /**
             * Format: date
             * @description 開始日
             */
            startDate?: string | null;
            /**
             * Format: date
             * @description 終了日
             */
            endDate?: string | null;
            /** @description ステータス */
            status: string;
            /** @description チケット完了条件 */
            completionCriteria: components["schemas"]["TicketCompletionCriterionResponse"][];
            /** @description チケットコメント */
            comments: components["schemas"]["TicketCommentResponse"][];
            /** @description チケット履歴 */
            histories: components["schemas"]["TicketHistoryResponse"][];
        };
        TicketCompletionCriterionResponse: components["schemas"]["AuditInfoResponse"] & {
            /**
             * Format: guid
             * @description チケット完了条件ID
             */
            id: string;
            /** @description 完了条件 */
            criterion: string;
            /** @description 完了状況 */
            isCompleted: boolean;
        };
        TicketCommentResponse: components["schemas"]["AuditInfoResponse"] & {
            /**
             * Format: guid
             * @description チケットコメントID
             */
            id: string;
            /**
             * Format: guid
             * @description 投稿者ID
             */
            authorId: string;
            /** @description コメント内容 */
            content: string;
        };
        TicketHistoryResponse: components["schemas"]["AuditInfoResponse"] & {
            /**
             * Format: guid
             * @description チケット履歴ID
             */
            id: string;
            /**
             * Format: guid
             * @description 実行者ID
             */
            actorId: string;
            /**
             * Format: date-time
             * @description 発生日時
             */
            occurredAt: string;
            /** @description 実行内容 */
            action: string;
            /** @description チケット履歴変更内容 */
            changes: components["schemas"]["TicketHistoryChangeResponse"][];
        };
        /** @description チケット履歴変更内容レスポンスDTO */
        TicketHistoryChangeResponse: {
            /** @description 変更項目 */
            field: string;
            /** @description 変更前 */
            before?: string | null;
            /** @description 変更後 */
            after?: string | null;
        };
        /** @description チケット作成リクエストDTO */
        CreateTicketRequest: {
            /** @description チケットタイトル */
            title: string;
            /** @description チケット説明 */
            description: string;
            /**
             * Format: guid
             * @description 担当者
             */
            assigneeId?: string | null;
            /**
             * Format: date
             * @description 開始日
             */
            startDate?: string | null;
            /**
             * Format: date
             * @description 終了日
             */
            endDate?: string | null;
            /** @description 完了条件 */
            completionCriteria?: string[];
            /** @description 通知対象ユーザー */
            notificationRecipientIds?: string[];
        };
        /** @description チケット編集リクエストDTO */
        UpdateTicketRequest: {
            /** @description チケットタイトル */
            title?: components["schemas"]["PatchFieldOfString"];
            /** @description チケット説明 */
            description?: components["schemas"]["PatchFieldOfString"];
            /** @description 担当者 */
            assigneeId?: components["schemas"]["PatchFieldOfNullableGuid"];
            /** @description 開始日 */
            startDate?: components["schemas"]["PatchFieldOfNullableDateOnly"];
            /** @description 終了日 */
            endDate?: components["schemas"]["PatchFieldOfNullableDateOnly"];
            /** @description ステータス */
            status?: components["schemas"]["PatchFieldOfString"];
            /** @description 完了条件 */
            completionCriterionOperations?: components["schemas"]["PatchFieldOfIReadOnlyListOfICompletionCriterionOperationDto"];
            /** @description コメント */
            comment?: components["schemas"]["PatchFieldOfString"];
            /** @description 通知対象ユーザー */
            notificationRecipientIds?: string[];
        };
        /** @description PATCH 用フィールド */
        PatchFieldOfString: {
            /** @description フィールドが JSON に明示的に含まれていたかどうか */
            isSpecified?: boolean;
            /** @description 指定された値 */
            value?: string | null;
        };
        /** @description PATCH 用フィールド */
        PatchFieldOfNullableGuid: {
            /** @description フィールドが JSON に明示的に含まれていたかどうか */
            isSpecified?: boolean;
            /**
             * Format: guid
             * @description 指定された値
             */
            value?: string | null;
        };
        /** @description PATCH 用フィールド */
        PatchFieldOfNullableDateOnly: {
            /** @description フィールドが JSON に明示的に含まれていたかどうか */
            isSpecified?: boolean;
            /**
             * Format: date
             * @description 指定された値
             */
            value?: string | null;
        };
        /** @description PATCH 用フィールド */
        PatchFieldOfIReadOnlyListOfICompletionCriterionOperationDto: {
            /** @description フィールドが JSON に明示的に含まれていたかどうか */
            isSpecified?: boolean;
            /** @description 指定された値 */
            value?: components["schemas"]["ICompletionCriterionOperationDto"][] | null;
        };
        ICompletionCriterionOperationDto: {
            type?: components["schemas"]["CompletionCriterionOperationType"];
        };
        /** @enum {string} */
        CompletionCriterionOperationType: "Add" | "Edit" | "Delete" | "Complete" | "Reopen";
        /** @description チケット完了条件追加リクエストDTO */
        AddCompletionCriterionRequest: {
            /** @description 完了条件 */
            criterion?: string;
        };
        /** @description チケット完了条件編集リクエストDTO */
        EditCompletionCriterionRequest: {
            /** @description 完了条件 */
            criterion?: string;
        };
        /** @description チケットコメント投稿リクエストDTO */
        AddTicketCommentRequest: {
            /** @description 担当者 */
            assigneeId?: components["schemas"]["PatchFieldOfNullableGuid"];
            /** @description 開始日 */
            startDate?: components["schemas"]["PatchFieldOfNullableDateOnly"];
            /** @description 終了日 */
            endDate?: components["schemas"]["PatchFieldOfNullableDateOnly"];
            /** @description ステータス */
            status?: components["schemas"]["PatchFieldOfString"];
            /** @description コメント */
            comment?: components["schemas"]["PatchFieldOfString"];
            /** @description 通知対象ユーザー */
            notificationRecipientIds?: string[];
        };
        /** @description チケットコメント編集リクエストDTO */
        EditTicketCommentRequest: {
            /** @description コメント内容 */
            content?: string;
        };
        UserResponse: components["schemas"]["AuditInfoResponse"] & {
            /**
             * Format: guid
             * @description ユーザーID
             */
            id: string;
            /** @description ユーザー名 */
            name: string;
            /** @description Eメール */
            email: string;
            /** @description システムロール */
            role: string;
        };
        /** @description ユーザー登録リクエストDTO */
        RegisterUserRequest: {
            /** @description 名前 */
            name: string;
            /** @description メールアドレス */
            email: string;
            /** @description パスワード */
            password: string;
            /** @description システムロール */
            role?: string;
        };
        /** @description ユーザー編集リクエストDTO */
        UpdateUserRequest: {
            /** @description 名前 */
            name?: string | null;
            /** @description メールアドレス */
            email?: string | null;
            /** @description パスワード */
            password?: string | null;
            /** @description システムロール */
            role?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Auth_Login: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Auth_Refresh: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Auth_Logout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Auth_GetMe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Projects_List: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Projects_Launch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchProjectRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Projects_GetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Projects_Delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Projects_Update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Projects_InviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Projects_RemoveMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                userId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Projects_ChangeMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                userId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeMemberRoleRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_List: {
        parameters: {
            query?: {
                /** @description タイトル */
                Title?: string | null;
                /** @description 担当者ID */
                AssigneeId?: string | null;
                /** @description ステータス */
                Status?: string | null;
                /** @description 開始日From */
                StartDateFrom?: string | null;
                /** @description 開始日To */
                StartDateTo?: string | null;
                /** @description 終了日From */
                EndDateFrom?: string | null;
                /** @description 終了日To */
                EndDateTo?: string | null;
                /** @description ページ番号 */
                PageNumber?: number;
                /** @description ページサイズ */
                PageSize?: number;
                /** @description ソート対象 */
                SortBy?: string | null;
                /** @description ソート順 */
                SortOrder?: components["schemas"]["SortOrder"];
            };
            header?: never;
            path: {
                projectId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponseOfTicketResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_Create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_GetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetailResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_Delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_Update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_AddCompletionCriterion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCompletionCriterionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_DeleteCompletionCriterion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                criterionId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_EditCompletionCriterion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                criterionId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditCompletionCriterionRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_CompleteCriterion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                criterionId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_ReopenCriterion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                criterionId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_AddComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTicketCommentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_DeleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                commentId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Tickets_EditComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                ticketId: string;
                commentId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditTicketCommentRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Users_ListAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Users_Register: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Users_Delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Users_Update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
